fp-matsuri/2025.fp-matsuri.org

README.md, content/_index.md
はてなブログのリンクを以下に修正しました。
https://blog.fp-matsuri.org/
またREADMEのリンクの表記を正しくしました。
=> Hatena Blogのリンク修正、READMEのリンク表記修正

content/_index.md, hugo-blox/blox/community/schedule.html
1/20より開始されているセッション募集の内容を反映した。
- トップページにセッション応募開始のリンクと日時を追加 
- トップページにセッション採択結果発表の予定を追加
=> セッション募集・結果発表のリンク・日時を追加

app/Route/Index.elm, app/Route/Slug_.elm, style.css
主に行動規範ページに適用している Markdown 向けの標準スタイルを整備します。
一部トップページにも適用していますが、こちらはなるべく見た目の変化が小さくなるように調整しています。
（デザイン面の更新はこのPRでは実施しません）
チケット：https://github.com/orgs/fp-matsuri/projects/1/views/2?pane=issue&itemId=96299851
行動規範①
行動規範②
トップページの変更差分
=> Markdown styles

app/Route/Index.elm, style.css
スポンサー募集セクションの拡充を前に、Teamセクションを簡単に調整します。
スタッフのアイコンを縮小する形でレイアウトを変更し、占有面積（高さ）を抑制します。
ここでは占有面積の縮小を優先し、簡単な検討に留めています。
実機などでの見た目の最適化は、後日別のPRで実施する見込みです。
チケット：https://github.com/orgs/fp-matsuri/projects/1?pane=issue&itemId=97347840
=> feat: Teamセクションの占有面積を小さくする

style.css
#30 で提案されていたようにスマホからの表示を調整します。
PC
スマホ
=> feat: Team セクションをスマホで表示した際に名前とアイコンが縦に並ぶようにする

app/Route/Index.elm
CFP終了した時点で応募中のボタンを変える必要があるので消してみました。
=> CFP終了時のメッセージ

style.css
- person のアイコンと名前が、画面幅に依らず縦に並ぶように変更した
- person の名前が、画面幅に依らず 14pt になるように変更した
Figma: https://www.figma.com/design/cpCoEPjZNHZdV3Z9cGkfDr
Figma に掲載されている幅 390px と 1440px でそれぞれ検証した
- アイコンと名前が縦に並んでいる
- フォントが 14pt
- アイコンと名前が縦に並んでいる
- フォントが 14pt
=> feat: Vertically align icon and name

app/Route/Index.elm, style.css
https://scalamatsuri.slack.com/archives/C07BETUT5V1/p1742340401894749 のフィードバックを受けて調整しました。
3/22追記：Sponsorsセクション以外の配色およびフォント指定の変更も併せて変更しました。
- 参考：[Figma](https://www.figma.com/design/cpCoEPjZNHZdV3Z9cGkfDr/Web%E3%82%B5%E3%82%A4%E3%83%88?node-id=1-25&t=UcWMQhjqXRMivziy-4)
=> feat: Sponsorsセクションの位置を調整 ＆ 配色を刷新

elm-review.json, elm.json, package-lock.json, package.json, review/elm.json, review/src/ReviewConfig.elm, tests/Example.elm
Elmでの開発に使う、Linter、Formatter、testのツールを入れました。
Linter: elm-review
Formatter: elm-format
Testing framework: elm-test
elm-formatのRuleは現状は空にしております。（一気に適用すると、Diffがすごくなりそうなので）
testも現状はからの状態です。
=> feat: add initial configuration files for linter, formatter and testing framework

app/Route/Index.elm
試しにNewsセクションを追加してみました。
|PC|Mobile|
|--|--|
|<img width=600 src=https://github.com/user-attachments/assets/f7a91e17-d368-4bf3-96b5-81f164409991>|<img width=240 src=https://github.com/user-attachments/assets/54ee9ad2-8351-4b21-a6ee-c8df522e95ef>|
以下の通り現状レイアウトが適当なのですが、ひとまずコードを頑張らない方向で書いています。
- セクションの上下(特に下)paddingがFigmaより小さい
- max width が決め打ちでem 32.5というマジックナンバーを使っている(`markdown` というクラスが使っている)
- スマホ判別のメディアクエリに関しても640と決め打ち
そのほかElmの書き方についてもよく知らないので何かあれば指摘もらえると助かります！
=> Newsセクションの追加

style.css
今後の情報量増加に備えて、LPのスタイルを次のように調整します
- サイトヘッダーロゴをひと回り縮小
- スマホで窮屈だったため調整
- .heroの高さを圧縮し、表示崩れを解消する
- スマホなどでコンテンツに対して高さが足りていなかったので、コンテンツの高さ基準で調整
- 添付画像のように下部アイコンとのギャップがなくなってしまっていたほか、さらに小さい端末では紺背景よりもはみ出していた
- セクションの基本スタイルを簡易に調整
- 余白や見出しの大きさを少しずつ縮小し、縦方向のスクロール量を抑える
=> feat: LPのスタイルを簡易に調整

app/Route/Index.elm
forteeの段階を次に進めた影響で https://fortee.jp/2025fp-matsuri/proposal/all がリンク切れになってしまったため、採択されたトークだけが表示されるURL https://fortee.jp/2025fp-matsuri/proposal/accepted に更新します
=> fix: 無効になったURLを最新化する

style.css
リネーム漏れを修正しようとしましたが、そもそもデフォルトで縦並びに配置されているので削除します
=> 不要なstyleを削除

app/Route/Index.elm
実装が共通している部分を、関数化し集約します。
- dividerを擬似要素に置き換え、独自のh3関数として共通化
- sponsorPlanを導入して共通部分を集約
=> refactor: Customized h3 tag

app/Route/Index.elm
https://www.notion.so/scalajp/Dev-1dc6d12253aa80b9adedd7e832eb296f
Befor:
After:
=> fix: Order of members

app/Route/Schedule.elm, src/Data/Schedule.elm
fortee側での更新に追従します。
- 最新のAPIに追従
- 不要になったハードコードを削除
- 補足情報を追加
- 「Track A, B, C共通で日本語字幕付きのセッション動画を投影する形式で行います」を表示
=> feat: Scottさんのトーク情報を更新

app/Route/Schedule.elm
タグのテキスト部分が上下中央揃えになっていない旨の指摘があったので、調整します。
https://scalamatsuri.slack.com/archives/C07SGLMRF8E/p1747833868046469
=> feat: タグのテキストを上下中央になるように調整

app/Api.elm
Googleにインデックスされな問題の対処の一環で、sitemap.xmlに記載されるURLの正規化を試してみます。
現行：https://2025.fp-matsuri.org/sitemap.xml
改修後のプレビュー： https://2025fp-matsuri-lii6801wd-keitans-projects.vercel.app/sitemap.xml
=> fix: sitemap.xmlの各URL末尾にスラッシュを追加する

app/Route/Index.elm
- 当日スタッフ募集案内への導線を削除
- News更新
- 当日スタッフの募集締め切り
- タイムテーブル公開（当時追加しそびれていたもの）
=> feat: 当日スタッフ募集の締め切りを通知＆動線削除

app/Route/Index.elm, style.css
トップページにコンテンツが増えてきたので、相対的に優先度の低いスタッフ一覧の表示を縮小します。
応援団のアイコンと同じサイズにしました。
=> feat: スタッフ一覧のアイコンサイズを縮小する

app/Route/Schedule.elm
タイムテーブルの表示について、次のように改修します：
改修前：モバイルファーストな実装の影響で印刷時の見た目がスマホと同じ表示になっていました
改修後：メディアクエリを調整し、印刷時にPCでの表示と同様の3カラムでの表現を可能にします
=> feat: 印刷を想定したメディアクエリを追加する

app/Shared.elm
#114 で付与したidを活用し、サイト内のナビゲーションからスケジュールページに遷移する場合にもDay2の部分を表示するように変更します。
=> feat: スケジュールページへのアクセス時にDay2を表示する
