content/authors/Iwaji/_index.md, content/authors/katsujukou/_index.md, content/authors/kmizu/_index.md, content/authors/lagenorhynque/_index.md, content/authors/omiend/_index.md, content/authors/yoshihiro503/_index.md, content/authors/ysaito8015/_index.md
https://www.notion.so/scalajp/1456d12253aa8019b807dde4537261ac
=> メンバーの追加 / 座長チームへの移動

content/_index.md, content/authors/Iwaji/_index.md, content/authors/igrep/_index.md, content/authors/katsujukou/_index.md, content/authors/kmizu/_index.md, content/authors/magnolia-k/_index.md, content/authors/quantumshiro/_index.md, content/authors/takezoux2/_index.md, content/authors/tanishiking/_index.md, content/authors/tomoco95/_index.md, content/authors/wm3/_index.md, content/authors/yonta/_index.md
タイトルの通りなのですが、作業が重複していたらマージせずにクローズしてもらっても構いません。
=> Teamのスタッフの部分をorganizer→スタッフへ

config/_default/params.yaml
https://docs.hugoblox.com/reference/seo/#improve-your-search-engine-and-social-network-previews
=> descriptionを更新

app/Api.elm, app/Effect.elm, app/ErrorPage.elm, app/Route/Index.elm, app/Route/Slug_.elm, app/Shared.elm
=> remove unused variables

README.md
初めてREADMEを見てセットアップしてみて、どのURLで立ち上がった開発サーバーにアクセスできるかわからなかったので追記しました。
=> 開発サーバー起動後 `http://localhost:1234/` でアクセスできることを明記

app/Route/Index.elm
現時点で掲載可能かつ、掲載されていないスタッフを追加します。
=> スタッフ一覧を 2025-03-02 の情報で更新する

package-lock.json, package.json
- elm-pages のバージョン更新
- `npm outdated` コマンドで利用可能な最新バージョンを確認しています。
- ローカル環境で動作に問題がないことを確認
=> chore: Update elm-pages

.github/workflows/preview.yaml, .gitignore
プルリクエストをVercelにデプロイするGithub Action
Next:
DEPLOY_URLをslack かプルリクに通知してみたい
=> Github Action: preview siteをデプロイする

.github/workflows/preview.yaml
preview url をプルリクに投稿する。
https://github.com/fp-matsuri/2025.fp-matsuri.org/pull/44#pullrequestreview-2707923803
=> comment preview url on pull request

app/Route/Index.elm
わたくしが座長メンバーとしてまったく活動できていないので、スタッフリストの方に移動させていただきました。
=> omiend Has been relocated from Chairs List to Staff List

app/Route/Index.elm, style.css
直近で追加いただいたロゴ表示部分とは別に、スポンサー募集メッセージ部分を中心にスタイル調整しました。
高さ方向の占有が少なくなるよう、文字サイズやボックスの最大幅を変更しています。
=> feat: Sponsorsセクションのスタイルを調整

app/Route/Index.elm, style.css
- heroのannouncement表示を削除
- Newsに項目追加
- NewsItem 型を導入（リファクタリング）
- scheduleSectionを廃止
=> feat: Newsにチケット販売開始の案内を追加する

.github/workflows/ci.yaml, package.json
=> ci: add github actions for ci

app/Route/Index.elm, app/Shared.elm
ページの階層によって画像を読み込めないことがあるので、相対パスを絶対パスに修正します。
=> fix: 画像のURL指定を絶対パスで記述する

app/Route/Index.elm
iframe 内の Google Map が英語モードになっていたのがちょっと気になったのでやってみました。
=> chore: 会場地図を日本語で表示

app/Route/Sponsors.elm
=> fix: スポンサーページの画像のリンク切れ

content/sponsors/nulab.md
=> fix: 正しいプラン指定に修正

app/Route/Index.elm, elm.json, src/FpMatsuri/BackgroundTexture.elm, src/FpMatsuri/Logo.elm
会場装飾やWebサイトなど汎用的に使えるテクスチャを模索する中で、一定の成果が出たのでPull Requestにしておきます。
=> feat: heroセクションの背景にランダムなパターンを表示する

app/Shared.elm, style.css
=> feat: スマホ向けにハンバーガーメニューを追加する

content/sponsors/platinum/3-shake.md
依頼のままにリンクを書き換えるだけなのでレビューは不要という判断をします。
=> スリーシェイクさまの記事のリンク先を変えて欲しいという依頼に対応

content/sponsors/silver/loglass.md
#99 にて発見したXアカウントのリンク切れについて、株式会社ログラス様と対応方針を確認できたので修正します。
https://scalamatsuri.slack.com/archives/C07SP75325R/p1748487886209979?thread_ts=1748483285.805389&cid=C07SP75325R
=> feat: 株式会社ログラスの広告にXのアカウントを追加

app/Route/Index.elm, app/Shared.elm
- 新着情報にスポンサーの募集を締め切ったことを追加
- スポンサー募集中のセクションをまるっと削除
- フッターにお問い合わせフォームへのリンクを追加
|Before|After|
|:--|:--|
|<img src="https://github.com/user-attachments/assets/54b44893-7742-44c6-8f69-c019467e268a" width=500>|<img src="https://github.com/user-attachments/assets/abec747c-6eca-4f0f-bad4-102f1d1c8a1a" width=500>|
|Before|After|
|:--|:--|
|<img src="https://github.com/user-attachments/assets/ff688144-d4f6-4155-bbe7-34c5318f8203" width=500>|<img src="https://github.com/user-attachments/assets/fa65e9df-43f4-4361-b0f7-eb574dfb6695" width=500>|
|Before|After|
|:--|:--|
|<img src="https://github.com/user-attachments/assets/0806265b-08f3-454f-b71c-3bf852dfbed3" width=300>|<img src="https://github.com/user-attachments/assets/62c46482-e239-4b88-927b-a7adce69340a" width=300>|
=> スポンサー募集を終了する

app/Route/Index.elm
懇親会チケットは販売終了しているので、サイト上からも情報を削除します。
=> feat: 懇親会チケット販売終了

content/sponsors/personal_supporter/fukuokaex.md
軽微な更新のため、セルフレビューでマージします。
https://scalamatsuri.slack.com/archives/C07SP75325R/p1749280046602809?thread_ts=1748935851.444669&cid=C07SP75325R
=> chore: fukuoka.ex のリンク先を更新

content/code-of-conduct.md, style.css
=> feat: 行動規範の動画リンクを関数型まつりのチャンネルに変更する

app/Route/Schedule.elm
Day 2の時にタイムテーブルへのリンクを貼ろうと思っていて、その時に https://2025.fp-matsuri.org/schedule#day2 へのリンクを貼った時にDay 2までスクロールさせようかと考えています。
=> タイムテーブルのヘッダ部分にIDを付与
